// js_utils.js - generated by js_utils
(function (root) {
    "use strict";
    function addStaticWebServerJsUtilsFiles(server) {
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Client.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Executor.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/HashLists.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/jsonfx.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/math.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/ObjectPositionSystem.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Regex.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Sorting.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/SqlHelper.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Utilities.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Core.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/ContentManager.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/Common.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/hmi_object.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/DataPoint.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/TargetSystem.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/WebSocketConnection.js');
        server.AddStaticFile('./node_modules/@markus.hardardt/js_utils/src/DataConnector.js');
    }
    const js_utils = {
        Client: require('./src/Client.js'),
        Executor: require('./src/Executor.js'),
        HashLists: require('./src/HashLists.js'),
        jsonfx: require('./src/jsonfx.js'),
        math: require('./src/math.js'),
        ObjectPositionSystem: require('./src/ObjectPositionSystem.js'),
        Regex: require('./src/Regex.js'),
        Server: require('./src/Server.js'),
        Sorting: require('./src/Sorting.js'),
        SqlHelper: require('./src/SqlHelper.js'),
        Utilities: require('./src/Utilities.js'),
        Core: require('./src/Core.js'),
        WebServer: require('./src/WebServer.js'),
        ContentManager: require('./src/ContentManager.js'),
        Common: require('./src/Common.js'),
        hmi_object: require('./src/hmi_object.js'),
        DataPoint: require('./src/DataPoint.js'),
        TargetSystem: require('./src/TargetSystem.js'),
        WebSocketConnection: require('./src/WebSocketConnection.js'),
        DataConnector: require('./src/DataConnector.js'),
        addStaticWebServerJsUtilsFiles
    };
    Object.seal(js_utils);
    module.exports = js_utils;
}(globalThis));
