(function (root) {
    "use strict";
    const Helper = {};
    const isNodeJS = typeof require === 'function';
    const fs = isNodeJS ? require('fs') : undefined;
    const Regex = isNodeJS ? require('../src/Regex.js') : undefined;
    const Core = isNodeJS ? require('../src/Core.js') : undefined;

    // TODO: Must be modified if file structure changed. This is a very simple solution so far
    const moduleNameRegex = /^([a-zA-Z][_a-zA-Z0-9]*)\.js$/;
    const moduleRegex = /\bconst\s+([a-zA-Z][_a-zA-Z0-9]*)\s*=\s*isNodeJS\s*\?\s*require\s*\(\s*'\.\/\1\.js'\s*\)\s*:\s*root\s*\.\s*\1\s*;/g;

    function loadDependencies(directory, ignorables, onSuccess, onError) {
        fs.readdir(directory, (error, files) => {
            if (error) {
                onError(error);
                return;
            }
            const dependencies = {};
            for (let file of files) {
                const match = moduleNameRegex.exec(file);
                if (!match) {
                    continue;
                }
                const moduleName = match[1];
                if (ignorables.indexOf(moduleName) >= 0 )  {
                    continue;
                }
                dependencies[moduleName] = [];
                const text = fs.readFileSync(`${directory}/${file}`, 'utf8');
                Regex.each(moduleRegex, text, (start, end, match) => dependencies[moduleName].push(match[1]), true);
            }
            onSuccess(dependencies);
        });
    }
    Helper.loadDependencies = loadDependencies;


    /*  Generates index.js */
    function generateIndexJs(name, scope, components, browserIgnorables) {
        let txt = `// ${name}.js - generated by js_utils\n`;
        txt += `(function (root) {\n`;
        txt += `    "use strict";\n`;

        txt += `    function addStaticWebServerFiles(server) {\n`;
        for (let component of components) {
            if (browserIgnorables.indexOf(component) < 0) {
                txt += `        server.AddStaticFile('./node_modules/${scope}js_utils/src/${component}.js');\n`;
            }
        }
        txt += `    }\n`;
        txt += `    const ${name} = {\n`;
        for (let component of components) {
            txt += `        ${component}: require('./src/${component}.js'),\n`;
        }
        txt += `        addStaticWebServerFiles\n`;
        txt += `    };\n`;
        txt += `    Object.seal(${name});\n`;
        txt += `    module.exports = ${name};\n`;
        txt += `}(globalThis));\n`;
        return txt;
    }
    Helper.generateIndexJs = generateIndexJs;

    /*  Helps writing new moduls*/
    function generateLibraryFileAccess(dependencies, scope = '@markus.hardardt/') {
        const components = Core.getTopologicalSorting(dependencies);
        let txt = ``;
        // Code usable js_utils internal
        txt += `    // ### inside js_utils ###\n\n`;
        for (const file in dependencies) {
            if (dependencies.hasOwnProperty(file)) {
                txt += `    // ==> file: '${file}.js':\n`;
                txt += `    const ${file} = {};\n`;
                txt += `    const isNodeJS = typeof require === 'function';\n`;
                const used = dependencies[file];
                for (let comp of components) {
                    if (used.indexOf(comp) >= 0) {
                        txt += `    const ${comp} = isNodeJS ? require('./${comp}.js') : root.${comp};\n`;
                    }
                }
                txt += `\n`;
            }
        }
        txt += `\n`;
        txt += `    // access js_utils components on node js:\n`;
        txt += `    // compact:\n`;
        txt += `    const {\n`
        for (let i = 0; i < components.length; i++) {
            txt += `        ${components[i]}${(i < components.length - 1 ? ',' : '')} // direct access: const ${components[i]} = require('${scope}js_utils/src/${components[i]}.js');\n`;
        }
        txt += `    } = require('${scope}js_utils/js_utils.js');\n`;
        txt += `    // separated:\n`;
        for (let comp of components) {
            txt += `    const ${comp} = require('${scope}js_utils/src/${comp}.js');\n`;
        }
        txt += `\n`;
        txt += `    // js_utils files for browser provided by webserver:\n`;
        for (let comp of components) {
            txt += `    webServer.AddStaticFile('./node_modules/${scope}js_utils/src/${comp}.js');\n`;
        }
        return txt;
    }
    Helper.generateLibraryFileAccess = generateLibraryFileAccess;

    /*  analyse js_utils library */
    function analyseLibrary(directory, output, index_js) {
        // TODO: Must be modified if file structure changed. This is a very simple solution so far
        const moduleNameRegex = /^([a-zA-Z][_a-zA-Z0-9]*)\.js$/;
        const moduleRegex = /\bconst\s+([a-zA-Z][_a-zA-Z0-9]*)\s*=\s*isNodeJS\s*\?\s*require\s*\(\s*'\.\/\1\.js'\s*\)\s*:\s*root\s*\.\s*\1\s*;/g;
        fs.readdir(directory, (error, files) => {

            let txt = `/* analyse directory: ${directory} */\n\n`;
            txt += '/* js_utils dependencies */\n';
            txt += 'const dependencies = {\n';
            for (const m in dependencies) {
                if (dependencies.hasOwnProperty(m)) {
                    txt += `  '${m}': [${dependencies[m].map(e => `'${e}'`).join(', ')}],\n`;
                }
            }
            txt += '};\n\n';
            txt += '/* topological sorting */\n';
            txt += 'const topologicalSortedComponents = [\n';
            for (let i = 0; i < topologicalSortedComponents.length; i++) {
                if (i > 0) {
                    txt += ',\n';
                }
                txt += `   ${topologicalSortedComponents[i]}`;
            }
            txt += '\n];\n\n';
            txt += '/* source code samples */\n';
            txt += generateLibraryFileAccess(dependencies);
            txt += `\n\n/* ${index_js} */\n`;
            txt += index;
            fs.writeFileSync(output, txt, 'utf8');
            if (index_js) {
                fs.writeFileSync(index_js, index, 'utf8');
            }
            console.log(`done (dumped: '${output}', exported: '${index_js}')`);
        });
    }
    Helper.analyseLibrary = analyseLibrary;

    Object.freeze(Helper);
    if (isNodeJS) {
        module.exports = Helper;
    } else {
        root.Helper = Helper;
    }
}(globalThis));
