import fs from 'node:fs';
import Regex from '../src/Regex.js';

const Helper = {};

// TODO: Must be modified if file structure changed. This is a very simple solution so far
const moduleNameRegex = /^([a-zA-Z][_a-zA-Z0-9]*)\.js$/;
const moduleRegex = /^\s*import\s+([a-zA-Z][_a-zA-Z0-9]*)\s+from\s+'\.\/([a-zA-Z][_a-zA-Z0-9]*)\.js'\s*;\s*$/mg;

function loadDependencies(directory, ignorables, onSuccess, onError) {
    fs.readdir(directory, (error, files) => {
        if (error) {
            onError(error);
            return;
        }
        const dependencies = {};
        for (let file of files) {
            const match = moduleNameRegex.exec(file);
            if (!match) {
                continue;
            }
            const moduleName = match[1];
            if (ignorables.indexOf(moduleName) >= 0) {
                continue;
            }
            dependencies[moduleName] = [];
            const text = fs.readFileSync(`${directory}/${file}`, 'utf8');
            Regex.each(moduleRegex, text, (start, end, match) => dependencies[moduleName].push(match[2]), true);
        }
        onSuccess(dependencies);
    });
}
Helper.loadDependencies = loadDependencies;

function formatDependencies(dependencies) {
    let txt = '';
    txt += 'const dependencies = {\n';
    for (const m in dependencies) {
        if (dependencies.hasOwnProperty(m)) {
            txt += `  '${m}': [${dependencies[m].map(e => `'${e}'`).join(', ')}],\n`;
        }
    }
    txt += '};\n';
    return txt;
}
Helper.formatDependencies = formatDependencies;

const addStaticWebServerFilesFunctionName = 'addStaticWebServerJsUtilsFiles';

const extRegex = /\/([_a-zA-Z][_a-zA-Z0-9\.]*)\.js$/;
/*  Generates index.js */
function generateIndexJs(name, scope, components, browserIgnorables, ext) {
    let txt = `// ${name}.js - generated by js_utils\n`;
    for (let component of components) {
        txt += `import ${component} from './src/${component}.js';\n`;
    }
    txt += '\n';

    txt += `function ${addStaticWebServerFilesFunctionName}(server, addMain) {\n`;
    const packageDirectory = `./node_modules/${scope}js_utils`;
    txt += `    server.addStaticDirectory('${packageDirectory}');\n`;
    txt += '    if (addMain) {\n';
    txt += `        server.addStaticModule('${packageDirectory}', 'client/main.js');\n`;
    txt += '    }\n';
    txt += '}\n';
    txt += 'const md5 = {};\n';
    txt += `const ${name} = {\n`;
    for (let component of components) {
        txt += `    ${component},\n`;
    }
    txt += '    md5, // external compatibility export\n';
    txt += `    ${addStaticWebServerFilesFunctionName}\n`;
    txt += '};\n';
    txt += `Object.seal(${name});\n`;
    txt += `export { ${components.join(', ')}, md5, ${name}, ${addStaticWebServerFilesFunctionName} };\n`;
    txt += `export default ${name};\n`;
    return txt;
}
Helper.generateIndexJs = generateIndexJs;

function generateInternalImports(dependencies, components) {
    let txt = '';
    txt += '    // ### inside js_utils ###\n\n';
    for (const file in dependencies) {
        if (dependencies.hasOwnProperty(file)) {
            txt += `    // file: '${file}.js':\n`;
            const used = dependencies[file];
            for (let component of components) {
                if (used.indexOf(component) >= 0) {
                    txt += `    import ${component} from './${component}.js';\n`;
                }
            }
            txt += '\n';
        }
    }
    return txt;
}
Helper.generateInternalImports = generateInternalImports;

function generateExternalImports(scope, components, ext) {
    let txt = '';
    txt += '    // access js_utils components with ES modules:\n';
    for (let component of components) {
        txt += `    import ${component} from '${scope}js_utils/src/${component}.js';\n`;
    }
    if (Array.isArray(ext)) {
        for (let e of ext) {
            const match = extRegex.exec(e);
            if (match) {
                txt += `    // ${match[1]} is exposed by the compatibility export.\n`;
            }
        }
    }
    txt += `    import { ${addStaticWebServerFilesFunctionName} } from '${scope}js_utils/js_utils.js';\n`;
    return txt;
}
Helper.generateExternalImports = generateExternalImports;

function formatTopologicalSortedComponents(components) {
    let txt = '';
    txt += '/* topological sorting */\n';
    txt += 'const topologicalSortedComponents = [\n';
    for (let i = 0; i < components.length; i++) {
        if (i > 0) {
            txt += ',\n';
        }
        txt += `   '${components[i]}'`;
    }
    txt += '\n];\n';
    return txt;
}
Helper.formatTopologicalSortedComponents = formatTopologicalSortedComponents;

Object.freeze(Helper);
export default Helper;
